# fly.toml app configuration file generated for full-stack-open-pokedex-old-haze-2361 on 2024-10-06T16:32:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-old-haze-2361'
primary_region = 'cdg'

[build]

[env]
  PORT = '3000'

[processes]
  app = 'node app.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
